import React, { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";

const SOURCE_LOGOS = {
  hackernews: "https://th.bing.com/th/id/OIP.EH5bPOmNgmmuIUoIa1wd9wHaFj?w=242&h=180&c=7&r=0&o=7&pid=1.7",
  techcrunch: "https://www.oii.ox.ac.uk/wp-content/uploads/2023/08/986342-scaled.webp",
  arxiv: "https://tse2.mm.bing.net/th/id/OIP.MDRJQ-QkTqZYDXAOw4Q59QHaEK?w=960&h=540&rs=1&pid=ImgDetMain",
  nvidia: "https://static.vecteezy.com/system/resources/previews/024/039/095/original/nvidia-logo-transparent-free-png.png",
  mit: "https://th.bing.com/th?q=MIT+Logo+Transparent+PNG&w=120&h=120&c=1&rs=1&qlt=70&o=7",
  nasa: "https://th.bing.com/th/id/OIP.lJOvaiqFmzmPHq8qNNVYGwHaHa?w=181&h=181&c=7&r=0&o=7",
  techradar: "https://tse3.mm.bing.net/th/id/OIP.pdBgF_RnmXpILmOwFXT-cQHaHa?rs=1&pid=ImgDetMain",
  medium: "https://cdn.mos.cms.futurecdn.net/xJGh6cXvC69an86AdrLD98.jpg",
  openai: "https://th.bing.com/th/id/OIP.AxEBHCVHQQoKms36-nGK3wHaHa?w=199&h=198&c=7&r=0&o=7",
};

const TeamMembers = [
  { name: "Aakash Kumar", img: "https://api.dicebear.com/9.x/bottts/svg?seed=Aakash" },
  { name: "Abhinav Singh", img: "https://api.dicebear.com/9.x/bottts/svg?seed=Abhinav" },
  { name: "Aditya Upadhyay", img: "https://api.dicebear.com/9.x/bottts/svg?seed=Aditya" },
  { name: "Anurag Shrivastav", img: "https://api.dicebear.com/9.x/bottts/svg?seed=Anurag" },
  { name: "Akhil Kumar", img: "https://api.dicebear.com/9.x/bottts/svg?seed=Akhil" },
];

const FAQS = [
  { q: "What does INSIGHT do?", a: "INSIGHT curates, summarizes, and ranks research papers, tech blogs, and trusted news sources personalized to your interests." },
  { q: "How often is the feed updated?", a: "Feeds update every 24 hours. You can also enable Weekly Digest for a weekly summary." },
  { q: "Is the AI summary accurate?", a: "Summaries are generated by AI optimized for clarity. Always consult original sources for accuracy." },
  { q: "Is there a mobile app?", a: "Our APK is under final testing — launching soon!" },
];

export default function Landing() {
  const navigate = useNavigate();
  const [email, setEmail] = useState("");
  const [suggestion, setSuggestion] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const canvasRef = useRef(null);

  // 🎨 Animated 3D particle background
  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");
    let width = (canvas.width = window.innerWidth);
    let height = (canvas.height = window.innerHeight);
    const colors = ["#C6B29A", "#D8C7B6", "#E4D5C9", "#F3E5D8", "#E7D0C5"];
    const particles = [];

    const createParticles = () => {
      for (let i = 0; i < 150; i++) {
        particles.push({
          x: Math.random() * width,
          y: Math.random() * height,
          radius: Math.random() * 2 + 1,
          color: colors[Math.floor(Math.random() * colors.length)],
          vx: (Math.random() - 0.5) * 0.6,
          vy: (Math.random() - 0.5) * 0.6,
        });
      }
    };

    const connectParticles = () => {
      for (let i = 0; i < particles.length; i++) {
        for (let j = i + 1; j < particles.length; j++) {
          const dx = particles[i].x - particles[j].x;
          const dy = particles[i].y - particles[j].y;
          const distance = Math.sqrt(dx * dx + dy * dy);
          if (distance < 120) {
            ctx.beginPath();
            ctx.strokeStyle = `rgba(80,60,40,${1 - distance / 120})`;
            ctx.lineWidth = 0.4;
            ctx.moveTo(particles[i].x, particles[i].y);
            ctx.lineTo(particles[j].x, particles[j].y);
            ctx.stroke();
          }
        }
      }
    };

    const animate = () => {
      ctx.clearRect(0, 0, width, height);
      for (let p of particles) {
        p.x += p.vx;
        p.y += p.vy;
        if (p.x < 0 || p.x > width) p.vx *= -1;
        if (p.y < 0 || p.y > height) p.vy *= -1;
        ctx.beginPath();
        ctx.arc(p.x, p.y, p.radius, 0, Math.PI * 2);
        ctx.fillStyle = p.color;
        ctx.fill();
      }
      connectParticles();
      requestAnimationFrame(animate);
    };

    createParticles();
    animate();

    const handleResize = () => {
      width = canvas.width = window.innerWidth;
      height = canvas.height = window.innerHeight;
    };
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleJoin = (e) => {
    e.preventDefault();
    if (!email) return alert("Please enter your email.");
    setSubmitted(true);
  };

  const handleSuggestion = (e) => {
    e.preventDefault();
    alert(`Thanks for your suggestion: "${suggestion}"`);
    setSuggestion("");
  };

  return (
    <div className="relative min-h-screen text-[#352414] font-sans overflow-x-hidden">
      <canvas ref={canvasRef} className="fixed inset-0 -z-10 bg-transparent" />

      {/* HERO */}
      <header className="pt-24 pb-16 text-center max-w-5xl mx-auto px-6">
        <h1 className="text-5xl md:text-6xl font-extrabold text-[#3b2a1a] drop-shadow-sm">
          Welcome to <span className="text-[#A47551]">INSIGHT</span> 🧠
        </h1>
        <p className="mt-5 text-lg text-[#4a3c28b3]">
          Discover smarter content, AI-curated updates, and deep insights tailored just for you.
        </p>

        {/* Highlighted Buttons */}
        <div className="mt-10 flex flex-wrap justify-center gap-5">
          <button
            onClick={() => navigate("/login")}
            className="bg-gradient-to-r from-[#C6B29A] to-[#E5D3B3] hover:scale-105 transition transform text-[#352414] font-bold px-8 py-3 rounded-full shadow-lg"
          >
            🚀 Join INSIGHT
          </button>
          <button
            onClick={() => navigate("/home")}
            className="border-2 border-[#A47551] hover:bg-[#A47551] hover:text-white px-8 py-3 rounded-full font-semibold transition"
          >
            🔍 Explore
          </button>
          <button
            onClick={() => alert("APK release in December! Stay tuned.")}
            className="bg-[#F8EFE0] border border-[#E5D3B3] hover:bg-[#FFF8F1] text-[#352414] px-8 py-3 rounded-full font-semibold transition"
          >
            📱 Download APK
          </button>
        </div>

        {/* Updated Notification */}
        <div className="mt-5 text-sm bg-[#FFF8F1]/70 border border-[#E5D3B3] px-5 py-2 rounded-full inline-block">
          🌍 Empowering creators, learners, and innovators — one insight at a time.
        </div>
      </header>

      {/* Who is INSIGHT for */}
      <section className="max-w-4xl mx-auto mt-10 px-6 text-center bg-[#fffaf3]/80 border border-[#e5d3b3] rounded-2xl shadow-md py-10">
        <h2 className="text-3xl font-bold mb-6">Who is INSIGHT for?</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-6">
          {["Students", "Researchers", "Working Professionals", "Entrepreneurs", "Developers", "Tech Enthusiasts"].map((role) => (
            <div key={role} className="bg-white p-4 rounded-xl border border-[#e5d3b3]">
              <span className="font-medium text-[#A47551]">{role}</span>
            </div>
          ))}
        </div>
      </section>
      
   {/* Features */}
        <section className="bg-[#F1EDE3] py-12">
          <div className="max-w-6xl mx-auto px-6 text-center">
            <h2 className="text-3xl font-bold">Key Features</h2>
            <div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                { title: "AI Summaries", desc: "Short, smart, and clear summaries." },
                { title: "Personalized Feed", desc: "Your interests decide your feed." },
                { title: "Cross-Source Synthesis", desc: "All major sources unified." },
                { title: "AI Digest", desc: "Daily or weekly highlights." },
                { title: "Save & Read Later", desc: "Organize your insights." },
                { title: "Expert Opinions", desc: "Top minds on trending ideas." },
              ].map((f) => (
                <div key={f.title} className="bg-white border border-[#e5d3b3] rounded-xl p-6 shadow-sm">
                  <h4 className="font-semibold">{f.title}</h4>
                  <p className="text-sm text-[#4a3c28b3] mt-2">{f.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

      {/* TEAM */}
      <section className="bg-[#F1EDE3] py-16 mt-20">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold">Meet the Team</h2>
          <div className="mt-8 grid grid-cols-2 md:grid-cols-5 gap-8">
            {TeamMembers.map((m) => (
              <div key={m.name} className="bg-white p-5 rounded-2xl border border-[#E5D3B3] shadow-md">
                <img src={m.img} alt={m.name} className="w-20 h-20 mx-auto rounded-full" />
                <p className="mt-3 font-semibold">{m.name}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="max-w-6xl mx-auto px-6 mt-20">
        <h2 className="text-3xl font-bold text-center">FAQ</h2>
        <div className="mt-6 space-y-4">
          {FAQS.map((f) => (
            <details key={f.q} className="bg-white p-4 border border-[#e5d3b3] rounded-xl">
              <summary className="font-medium">{f.q}</summary>
              <p className="text-sm text-[#4a3c28b3] mt-2">{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* Suggestion Box */}
      <section className="max-w-4xl mx-auto bg-[#F9F4EE] p-8 rounded-2xl border border-[#E5D3B3] mt-20 text-center">
        <h3 className="text-2xl font-semibold">💡 Got a feature idea?</h3>
        <p className="text-[#4a3c28b3] mt-2">We’d love to hear your thoughts and suggestions to improve INSIGHT.</p>
        <form onSubmit={handleSuggestion} className="mt-6 flex flex-wrap justify-center gap-3">
          <input
            type="text"
            placeholder="Share your idea..."
            value={suggestion}
            onChange={(e) => setSuggestion(e.target.value)}
            className="px-4 py-3 rounded-full border border-[#e5d3b3] w-64"
          />
          <button type="submit" className="bg-[#352414] text-white px-6 py-3 rounded-full font-semibold hover:scale-105 transition">
            Submit
          </button>
        </form>
      </section>

      {/* Newsletter */}
      <section className="bg-[#C6B29A] text-[#352414] py-12 mt-20 text-center">
        <h3 className="text-2xl font-bold">Join the INSIGHT</h3>
        <form onSubmit={handleJoin} className="mt-6 flex flex-wrap justify-center gap-3">
          <input
            type="email"
            placeholder="Your email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="px-4 py-3 rounded-full border border-[#e5d3b3]"
          />
          <button type="submit" className="bg-[#352414] text-white px-6 py-3 rounded-full font-semibold">
            Subscribe
          </button>
        </form>
        {submitted && (
          <p className="mt-3 bg-white px-4 py-2 rounded-full inline-block shadow-sm">
            Thanks — check {email} for your personalized digest (demo).
          </p>
        )}
      </section>

      <footer className="bg-[#E7D0C5] py-6 text-center text-sm">
        © {new Date().getFullYear()} INSIGHT — Built with ☕ by Team INSIGHTERS
      </footer>
    </div>
  );
}
